### ISSUE TITLE
Please create RTD project on readthedocs.org

### ISSUE THREAD

**Issue by JulienGuo** [hyperledger-labs/fabric-docs-cn#6]
@tkuhrt Hi, 
problem 1 : I can't create RTD project named "fabric-docs-cn", because of the name is occupied.
problem 2 : I can't set the connection between RTD and github , because of I can't change the repo's settings , we should set the GitHub incoming webhook at settings.
problem 3 : I have split the big translation task into smaller tasks in the old repo. If we start the repo , we need do the same thing , this thing will cost more 3 hours. do you known some functions in the github site about  transfer old project from old repo to here ?

**Comment by tkuhrt** [comment]
Long term, we would want the documentation to show up under http://hyperledger-fabric.readthedocs.io/cn/latest/ so that all off the Hyperledger Fabric documentation is under the same project. In the mean time, we may want to consider hyperledger-fabric-cn.readthedocs.io

If you can provide me with details on the webhook information, I can update the project.

We can only transfer from old project to new project if all of the commits have been signed with the -s option.

@ryjones FYI

**Comment by JulienGuo** [comment]
@tkuhrt I don't know who can relate RTD(http://hyperledger-fabric.readthedocs.io/cn/latest/) to this repo

**Comment by JulienGuo** [comment]
@tkuhrt I just created a RTD project it generate a webhook (https://readthedocs.org/api/v2/webhook/hyperledger-fabric-docs-cn/45711/), it looks good. AND , the  new RTD link is (https://hyperledger-fabric-docs-cn.readthedocs.io/en/1.2.0_zh-cn/) not (
http://hyperledger-fabric.readthedocs.io/cn/latest/)

**Comment by JulienGuo** [comment]
@tkuhrt Oh, the webhook can not trigger build action, you should add it to the repo webhooks.

**Comment by JulienGuo** [comment]
@tkuhrt if you can manage (http://hyperledger-fabric.readthedocs.io/cn/latest/). you can add that webhook link to this repo instead of add mine

**Comment by JulienGuo** [comment]
@tkuhrt Hi, I changed the webhook , the new one is (
https://readthedocs.org/api/v2/webhook/hyperledger-fabric-cn/46029/)
